services:
  squid-container:
    image: ubuntu/squid:latest
    container_name: squid-container
    restart: always
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./ips.txt:/etc/squid/ips.txt
      - ./log:/var/log/squid
      - ./squid.passwd:/etc/squid/squid.passwd
    ports:
      - 80:3128